// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw6yFsu2UtGRBi0iMXu5tD9-Z0b_z7o-U',
    appId: '1:406740472183:web:667782ab2a5cb9f512d172',
    messagingSenderId: '406740472183',
    projectId: 'doorapp-93356',
    authDomain: 'doorapp-93356.firebaseapp.com',
    storageBucket: 'doorapp-93356.appspot.com',
    measurementId: 'G-6K8WWVJ5NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHfzJVfSrsgMLmtKCtpSeC2kzga8fEkX8',
    appId: '1:406740472183:android:2250f41b06315d1612d172',
    messagingSenderId: '406740472183',
    projectId: 'doorapp-93356',
    storageBucket: 'doorapp-93356.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH8-s6dy4ducijyEC6WlYmF9XOVnHA3L0',
    appId: '1:406740472183:ios:fe69cd5e7b469efc12d172',
    messagingSenderId: '406740472183',
    projectId: 'doorapp-93356',
    storageBucket: 'doorapp-93356.appspot.com',
    androidClientId: '406740472183-ajhi3g4bb8slvtu5jk2dd19st21kq1bd.apps.googleusercontent.com',
    iosClientId: '406740472183-thuqi30t5704negatgjrg3q8fosilo7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.doorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH8-s6dy4ducijyEC6WlYmF9XOVnHA3L0',
    appId: '1:406740472183:ios:10b53cca179d01a512d172',
    messagingSenderId: '406740472183',
    projectId: 'doorapp-93356',
    storageBucket: 'doorapp-93356.appspot.com',
    androidClientId: '406740472183-ajhi3g4bb8slvtu5jk2dd19st21kq1bd.apps.googleusercontent.com',
    iosClientId: '406740472183-k8m8rp4t735ac1e20nigk4qhgnrh2ir0.apps.googleusercontent.com',
    iosBundleId: 'com.example.doorapp.RunnerTests',
  );
}
